name: Build

on:
  push:
  workflow_dispatch:

jobs:
  ExifGlass:
    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          path: './source'

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Nuget Restore
        run: nuget restore .\source\source\ExifGlass.sln

      - name: Build entire solution
        run: |
          cd "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\"
          .\MSBuild.exe $Env:GITHUB_WORKSPACE\source\source\ExifGlass.sln -p:Configuration=Release -p:Platform=x64 -p:RuntimeIdentifier=win-x64 -restore

      - name : Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ExifGlass
          path: |
            .\source\source\ExifGlass\bin\Publish\x64\*
